# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'macOS-latest'
 
variables:
  - name: 'DOCKER_REGISTRY'
    value: 'docker.io'
  - name: 'DOCKER_IMAGE_NAME' 
    value: 'my-docker-image'
  - name: 'DOCKER_IMAGE_TAG'
    value: 'latest'
  - name: 'DOCKER_IMAGE_NAME_WITH_TAG'
    value: '${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
